name: opencv-rust
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
      
defaults:
  run:
    shell: bash

jobs:
  opencv:
    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    runs-on: ${{ matrix.os }}
    



    steps:
      - uses: actions/checkout@v3
      - run: git clone https://github.com/opencv/opencv.git && cd opencv && git checkout 4.6.0
      - name: Cache OpenCV
        uses: actions/cache@v3
        with:
          path: opencv/build
          key: ${{ runner.os }}-opencv
      - run: mkdir -p opencv/build
      - run: cd opencv/build && cmake -DBUILD_SHARED_LIBS=off -DWITH_IPP=OFF -DOPENCV_FORCE_3RDPARTY_BUILD=on -DBUILD_LIST=core,dnn,imgcodecs -DCMAKE_INSTALL_PREFIX=install -DCMAKE_BUILD_TYPE=RELEASE -DWITH_OPENEXR=off -DWITH_TIFF=off -DWITH_WEBP=off -DWITH_OPENJPEG=off -DWITH_JASPER=off ..  && cmake --build . -j 8
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo run

    
