name: opencv-rust
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
      
defaults:
  run:
    shell: bash    



jobs:
  opencv:
    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    runs-on: ${{ matrix.os }}
    



    steps:
      - run: git clone https://github.com/opencv/opencv.git
      - run: mkdir -p opencv/build
      - run: cd opencv/build && cmake -DBUILD_SHARED_LIBS=off -DWITH_IPP=OFF -DBUILD_LIST=core,dnn,imgcodecs -DCMAKE_INSTALL_PREFIX=install -DCMAKE_BUILD_TYPE=RELEASE -DWITH_OPENEXR=off -DWITH_TIFF=off -DWITH_WEBP=off -DWITH_OPENJPEG=off -DWITH_JASPER=off ..  && cmake --build . -j 8 && make install


    
